# This is a basic workflow to help you get started with Actions
name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          
      - name: Maven Build
        run: |
          cd my-app
          mvn versions:set -DnewVersion=1.0.${{ github.run_number }}
          mvn -B  clean package 
          mkdir artifact && cp target/*.jar artifact
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-app
          path: my-app/artifact
          
      - uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}    
      
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:1.0.${{ github.run_number }}
          
      - name: Test Docker Image
        run: |
          docker run ${{ secrets.DOCKER_USERNAME }}/my-app:1.0.${{ github.run_number }}
        
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:1.0.${{ github.run_number }}   
          
  
