# This is a basic workflow to help you get started with Actions
name: CI-2
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}    
      
      - name: Build Docker image
        run: 
          docker build -f Dockerfile2 -t ${{ secrets.DOCKER_USERNAME }}/my-app:1.0.${{ github.run_number }} --build-arg PATCH=${{ github.run_number }} .
          
      - name: Test Docker Image
        run: |
          docker run ${{ secrets.DOCKER_USERNAME }}/my-app:1.0.${{ github.run_number }}
        
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:1.0.${{ github.run_number }}   
          
  
